coverage:
  status:
    project:
      default:
        target: 80% # or your target %
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "project, reach, diff, files"
  behavior: default
  require_changes: false
